Recreatus/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'), name='app')
]

handler404 = 'app.errors.not_found'
handler400 = 'app.errors.bad_request'
handler500 = 'app.errors.server_error'

app/urls.py
from django.urls import path, include
from . import views

app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),
    path('private_events/', views.private_events, name='private_events'),
    path('signup/', views.signup, name='signup'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('event/<int:pk>/', views.event_detail, name='event_detail'),
    path('event/create/', views.create_event, name='create_event'),
    path('user/<int:pk>/', views.user_detail, name='user_detail'),
    path('user/edit/', views.edit_profile, name='edit_profile'),
    path('event/<int:pk>/participation/', views.participation, name='participation'),
    path('event/<int:pk>/comment/', views.comment, name='comment'),
    path('event/<int:pk>/rate', views.rate_event, name='rate_event'),
    path('user/<int:pk>/follow/', views.follow_user, name='follow_user'),
    path('event/<int:event_id>/invite_users/', views.invite_users, name='invite_users'),
    path('search/', views.search, name='search')
]

app/templates/_event.html
<a href="{% url 'app:event_detail' event.id %}" class="list-group-item list-group-item-action mb-2">
    <div class="d-flex w-100 justify-content-between">
        <h4 class="mb-1">{{ event.title }}</h4>
        <small class="text-muted">From: {{ event.start_time }}</small>
        <small class="text-muted">To: {{ event.end_time }}</small>
    </div>
    <div>
        <p>Hosted by: {{ event.owner.user.username }}</p>
        <p class="mb-1">{{ event.description }}</p>
        <p>Number of participants: {{ event.participants.count }}</p>
    </div>
</a>

app/templates/_user.html
<a href="{% url 'app:user_detail' user.id %}" class="list-group-item list-group-item-action mb-2">
    <div class="d-flex w-100 justify-content-between">
        <h4 class="mb-1">{{ user.username }}</h4>
        <small class="text-muted">Last seen: {{ user.profile.last_online }}</small>
    </div>
    <div>
        <p>Events hosted: {{ user.profile.hosted_events.count }}</p>
        <p>Events participated: {{ user.profile.events_participating.count }}</p>
        <p class="mb-1">About me: {{ user.profile.bio }}</p>
    </div>
</a>

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>

    <link rel="stylesheet" href="https://bootswatch.com/4/lux/bootstrap.css" >
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
<body>
    {% load tz %}
    {% localtime on %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <a class="navbar-brand" href="{% url 'app:index' %}">Recreatus</a>
        <a class="nav-link" href="{% url 'app:index' %}">Home<span class="sr-only">(current)</span></a>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

            {% if user.is_authenticated %}
                <form class="form-inline my-2 my-lg-0" method="get" action="{% url 'app:search' %}">
                  <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="query">
                  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                  <select class="custom-select mr-sm-1" id="inlineFormCustomSelect" name="type">
                    <option selected value="events">Events</option>
                    <option value="users">Users</option>
                  </select>
                </form>
            {% endif %}
        </ul>
          {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'app:private_events' %}">Private events<span class="sr-only">(current)</span></a>
            <a class="nav-link" href="{% url 'app:create_event' %}">Create event<span class="sr-only">(current)</span></a>
            <a class="nav-link" href="{% url 'app:user_detail' request.user.id %}">My Profile<span class="sr-only">(current)</span></a>
            <a class="nav-link" href="{% url 'app:logout' %}">Log out</a>
          {% else %}
              <a class="nav-link" href="{% url 'app:login' %}">Log in<span class="sr-only">(current)</span></a>
              <a class="nav-link" href="{% url 'app:signup' %}">Sign up</a>
          {% endif %}
      </div>
    </nav>

    <div class="container">
        {% if messages %}
            {% for message in messages %}
                {% if message.level == DEFAULT_MESSAGE_LEVELS.INFO %}
                    <div class="alert alert-primary" role="alert">{{ message }}</div>
                {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                    <div class="alert alert-success" role="alert">{{ message }}</div>
                {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                    <div class="alert alert-danger" role="alert">{{ message }}</div>
                {% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
                    <div class="alert alert-warning" role="alert">{{ message }}</div>
                {% endif %}
            {% endfor %}
        {% endif %}
        {% block content %}
        {% endblock %}
    </div>

    {% endlocaltime %}
</body>
</html>

app/templates/create_event.html
{% extends 'base.html' %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ create_event_form.as_p }}
        <button type="submit" >Create event</button>
    </form>
{% endblock %}

app/templates/edit_profile.html
{% extends 'base.html' %}

{% block content %}
    <h2>{{ request.user.username }}</h2>
    <form method="post">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <button type="submit">Save changes</button>
    </form>
{% endblock %}

app/templates/event_detail.html
{% extends 'base.html' %}

{% block content %}
    <h2 class="mb-2" >{{ event.title }}</h2>
    <p>Starts at: {{ event.start_time }}</p>
    <p>Ends at: {{ event.end_time }}</p>
    <p>Hosted by: <a href="{% url 'app:user_detail' event.owner.user.id %}">{{ event.owner.user.username }}</a></p>

    {% if event.public_flag %}
        <p>Public event</p>
    {% else %}
        <p>Private event</p>
    {% endif %}

    <p class="mb-2" >{{ event.description }}</p>

    {% if should_rate %}
        <form method="post" action="{% url 'app:rate_event' event.id %}">
            {% csrf_token %}
            {{ rate_form.as_p }}
            <button type="submit">Rate</button>
        </form>
    {% endif %}

    {% if not event_ended %}
        {% if event.owner == request.user.profile %}
            Invite users:
            <form method="post" action="{% url 'app:invite_users' event.id %}">
            {% csrf_token %}
                <select name="invited_users" multiple>
                    {% for user_to_invite in users_to_invite.all %}
                        <option value="{{ user_to_invite.user.id }}">{{ user_to_invite.user.username }}</option>
                    {% endfor %}
                </select>
                <button type="submit">Invite</button>
            </form>
        {% endif %}

        {% if request.user.profile not in event.participants.all %}
            <a href="{% url 'app:participation' event.id %}?participation=true">Participate event</a>
        {% else %}
            <a href="{% url 'app:participation' event.id %}?participation=false">I will not participate event</a>
        {% endif %}
        <h5>Participants</h5>
        {% if event.participants.count > 0 %}
            <ul>
                {% for profile in event.participants.all %}
                    <li><a href="{% url 'app:user_detail' profile.user.id %}">{{ profile.user.username }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No participants yet</p>
        {% endif %}
    {% endif %}

    <h3>Comments</h3>
    {% if event.comments.count > 0 %}
        <ul class="list-groups">
            {% for comment in event.comments.all %}
                    <li class="list-group-item">
                        {{ comment.posted_on }}
                        <a href="{% url 'app:user_detail' comment.owner.user.id %}">{{ comment.owner.user.username }}</a>
                        said: {{ comment.content }}
                    </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No comments</p>
    {% endif %}

    <form method="post" action="{% url 'app:comment' event.id %}">
        {% csrf_token %}
        {{ comment_form.as_p }}
        <button type="submit">Comment</button>
    </form>

{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
    {% if events_page.object_list %}
        <div class="list-group">
            {% for event in events_page.object_list %}
                {% include '_event.html' %}
            {% endfor %}
        </div>
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-around">
                <li class="page-item {% if not events_page.has_previous %} disabled{% endif %}">
                    <a class="page-link" href="{% url 'app:index' %}{% if events_page.has_previous %}?page={{ events_page.previous_page_number }}{% endif %}">Newer events</a>
                </li>
                <li class="page-item {% if not events_page.has_next %} disabled{% endif %}">
                    <a class="page-link" href="{% url 'app:index' %}{% if events_page.has_next %}?page={{ events_page.next_page_number }}{% endif %}">Older events</a>
                </li>
            </ul>
        </nav>
    {% else %}
        <p>No events are available.</p>
    {% endif %}
{% endblock %}

app/templates/search.html
{% extends 'base.html' %}

{% block content %}
    {% if page.object_list %}
        <div class="list-group">
            {% if type == 'users' %}
                {% for user in page.object_list %}
                    {% include '_user.html' %}
                {% endfor %}
            {% elif type == 'events' %}
                {% for event in page.object_list %}
                    {% include '_event.html' %}
                {% endfor %}
            {% endif %}
        </div>
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-around">
                <li class="page-item {% if not page.has_previous %} disabled{% endif %}">
                    <a class="page-link" href="{% url 'app:search' %}?{% if page.has_previous %}page={{ page.previous_page_number }}&{% endif %}{{ url_params }}">Newer events</a>
                </li>
                <li class="page-item {% if not page.has_next %} disabled{% endif %}">
                    <a class="page-link" href="{% url 'app:search' %}?{% if page.has_next %}page={{ page.next_page_number }}&{% endif %}{{ url_params }}">Older events</a>
                </li>
            </ul>
        </nav>
    {% else %}
        <p>No events are available.</p>
    {% endif %}
{% endblock %}

app/templates/user_detail.html
{% extends 'base.html' %}

{% block content %}
    <h2>{{ user.username }}</h2>
    <h4>User rating: {{ rating }}</h4>
    <p>Email: {{ user.email }}</p>
    <p>About me: {{ user.profile.bio }}</p>
    <p>Last online: {{ user.profile.last_online }}</p>

    {% if request.user == user %}
        <a href="{% url 'app:edit_profile' %}">Edit profile</a>
    {% elif user.profile not in request.user.profile.following.all %}
        <a href="{% url 'app:follow_user' user.id %}?follow=true" >Follow</a>
    {% else %}
        <a href="{% url 'app:follow_user' user.id %}?follow=false" >Unfollow</a>
    {% endif %}
    <h5>Users following</h5>
    {% if user.profile.following.count > 0 %}
        <ul>
            {% for profile in user.profile.following.all %}
                <li><a href="{% url 'app:user_detail' profile.user.id %}">{{ profile.user.username }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No following users</p>
    {% endif %}

    <h5>Hosted events</h5>
    {% if user.profile.hosted_events.count > 0 %}
        <ul>
            {% for event in user.profile.hosted_events.all %}
                {% include '_event.html' %}
            {% endfor %}
        </ul>
    {% else %}
        <p>No hosted events</p>
    {% endif %}

    <h5>Participated events</h5>
    {% if user.profile.events_participating.count > 0 %}
        <ul>
            {% for event in user.profile.events_participating.all %}
                {% include '_event.html' %}
            {% endfor %}
        </ul>
    {% else %}
        <p>No events participated</p>
    {% endif %}

{% endblock %}